package br.com.fiap.cp1.entity;

public enum Genero {
	
	ACAO, HORROR, COMEDIA, FICCAO_CIENTIFICA, ROMANCE, DOCUMENTARIO, MUSICAL, ANIMACAO, COMEDIA_ROMANTICA, FAROESTE,
	GUERRA, AVENTURA, DRAMA, COMEDIA_DRAMATICA, INDIE, SUSPENSE, SOBRENATURAL, FANTASIA;
	
}
